### ISSUE TITLE
OauthAccessTokenMappings request returns a list instead of a dict

### ISSUE THREAD

**Issue by TrevJohnson** [Py-Ping/py-ping-fed-sdk#11]
Issue encountered generating SDK for Ping Federate V 11.0.2.0

 - `OauthAccessTokenMappings.getMappings()` returns a list, the expected result is a dictionary.

**Comment by teddevaal** [comment]
Issue can be resolved by adding a condition to validate the response:
```
if type(response.json()) == list:
    response_dict = {'items': response.json()}
return ModelAccessTokenMappings.from_dict(response_dict)
```
