### ISSUE TITLE
no enums are being generated when running docker-generate edge

### ISSUE THREAD

**Issue by evdmaas** [Py-Ping/py-ping-fed-sdk#3]
enums.py doesn't contain any classes when running docker_generate.py edge. Running generate against a FP10.x instance generates a whole bunch of enum classes, but this appear to be happening when running against a PF11 instance.

**Comment by teddevaal** [comment]
Hi Ed,

As of PF11, Ping has removed the reference to any definitions of enumerations in their Swagger file. Therefore, the class generation for enums.py needs to be enhanced.

A feature branch has been created that allows for testing this functionality (https://github.com/Py-Ping/py-ping-fed-sdk/tree/feature/enums).

**Comment by evdmaas** [comment]
thanks Ted, this branch has fixed the issue

**Comment by teddevaal** [comment]
Awesome, I'm glad to hear. I will create a Pull Request to move this enhancement to master.
