### ISSUE TITLE
api endpoint paths are not generated properly

### ISSUE THREAD

**Issue by evdmaas** [Py-Ping/py-ping-fed-sdk#4]
the API endpoint URLs are not generated properly for all APIs.

For example, /KeyPairs/signing has 13 endpoints of which 12 have a subpath (for example /KeyPairs/signing/{id}) but in the KeyPairsSigning class in key_pairs_signing.py, everything is point to the base URL /keyPairs/signing. None of the subpaths are appended.

**Comment by teddevaal** [comment]
Hi @evdmaas,

The new construct that is being used for PF11 was still using the 'old' API path. This has been resolved in https://github.com/Py-Ping/py-ping-fed-sdk/tree/fix/api-endpoint-paths. If you can do some testing in this branch to make sure that it is working for you, that would be great. Thanks.

**Comment by evdmaas** [comment]
Hi @teddevaal,

This branch seems to be resolving the issues for API paths. So far testing has been positive.
