### ISSUE TITLE
PF11 - duplicate API names are appended with a sequence number

### ISSUE THREAD

**Issue by evdmaas** [Py-Ping/py-ping-fed-sdk#5]
Hi,

Duplicate API function names are being appended with sequence names even tho if they belong to different APIs. For example:
KeyPairsSigning.getKeyPairs_1()
KeyPairsSslClient.getKeyPairs_2()
KeyPairsSslServer.getKeyPairs_3()

If the swagger would ever change the order of the APIs and you generate a new client it could break your existing code as the sequence numbers could change. Ideally the sequence numbers would get dropped.

Cheers

**Comment by teddevaal** [comment]
Hi @evdmaas,

These function names are coming directly from the Swagger file. The SDK does not interfere with the methods that are being generated using these Operation IDs, nor does it add sequencing.
